# -*- coding: utf-8 -*-
"""Gestion de Bibliothèques avec NoSQL - Groupe 2 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HqCcbwKmM47PX75VJQ-MZMk65uNA2tZH

# Installation des librairies utilisées (pymongo, autres via pip install)
"""# Importation des bibliothèques nécessaires"""

from pymongo import MongoClient
from scripts_nosql import insertions_initiales, aggregations_de_donnees, creation_index

"""# Creation et accès à la base de données MongoDB"""

client = MongoClient("mongodb://localhost:27017/")
db = client["bibliotheque_numerique"]

"""# Creation des collections"""
collections = ["Auteurs","Livres", "Utilisateurs","Emprunts"]

for collection in collections:
    if collection not in db.list_collection_names():
        db.create_collection(collection)
        print(f"La collection {collection} a été créée avec succès.")
    else:
        print(f"La collection {collection} existe déjà.")

print("*******"*10)
"""# Operations CRUD (Insertion de documents dans les collections)"""
# Insertions des documents (Livres, auteurs, emprunts, utilisateurs)
insertions_initiales.insert_all_documents(db)

print("*******"*10)
# Mise à jour d'un livre avec le statut de disponibilité = False
isbn = '978-2-07-036002-4'
insertions_initiales.mis_a_jour_disponibilite_livre(db, isbn, False)

print("*******"*10)

"""# Creation des Indexes utiles"""
creation_index.index_titre_livre(db)

champs_a_indexer = [
    ("id_utilisateur", 1),
    ("date_retour_effective", 1),
    ("date_emprunt", -1)
]

# Creation index composé pour optimiser une requête sur la collection emprunts
creation_index.index_compose(db,"Emprunts",champs_a_indexer)

# Extraction de données par requêtage

print("*******"*10)

aggregations_de_donnees.nombre_livres_par_auteur(db)


print("*******"*10)

aggregations_de_donnees.liste_livres_emprunts_encours(db)